### ISSUE TITLE
Jenkins Sample

### ISSUE THREAD

**Issue by regicsolutions** [tsteenbakkers/MSSQL-CICD-Helper#6]
Would you happen to have a sample Jenkinsfile?

**Comment by tsteenbakkers** [comment]
Hi,

This repo and solution is not actively maintained so a jenkinsfile is not available. Also this was developed quite some years ago and I've moved away from Jenkins based cicd setups over time so I can't help you there unfortunately.

**Comment by regicsolutions** [comment]
Thanks for the reply
